version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/myfolder/index.js
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
