version: '3.7'

# 명령어
# docker-compose build
# docker-compose up
# ctrl+c || docker-compose stop

# 컴퓨터들
services:
  # 컴퓨터 이름
  my-backend:
    image: asia.gcr.io/backend-408219/my-backend-project-nestjs:0.7
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # ports:
    #   - 3000:3000
    # env_file:
    #   - ./.env.prod
  # 컴퓨터 이름
  # my-database:
  #   # Dockerfile 에 한 줄만 쓰여지는 경우 image로 추가해주면 됨.
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker' # mysql이 실행되고, "mydocker" 라는 데이터베이스가 생성됨.
  #     MYSQL_ROOT_PASSWORD: 'root' # mysql 실행되고 root 비밀번호를 "root"로 설정
  #   ports:
  #     - 3306:3306
    #                     하지만, 네임리졸루션으로 express에서는 접속 됨.
# 주의!! :
#   1. 컴퓨터 이름은 lowercase 로 작성
#   2. ports 는 build 와 같은 라인에
