version: "3.7"

# 명령어
# docker-compose build
# docker-compose up
# ctrl+c || docker-compose stop

# 컴퓨터들
services:
  # 컴퓨터 이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  # 컴퓨터 이름
  my-database:
    # Dockerfile 에 한 줄만 쓰여지는 경우 image로 추가해주면 됨.
    image: mongo:5
    ports:
      - 27017:27017 # ==> mongodb-compass 에서 접속 안됨.
    #                     하지만, 네임리졸루션으로 express에서는 접속 됨.
# 주의!! :
#   1. 컴퓨터 이름은 lowercase 로 작성
#   2. ports 는 build 와 같은 라인에
